# Generated by Django 4.2.7 on 2024-05-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_podcast_song_userplaylist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Podcast',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.DeleteModel(
            name='UserPlaylist',
        ),
    ]
